//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MessagePack.Attributeless.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MessagePack.Attributeless.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BaseTypeFormatter_template {
            get {
                return ResourceManager.GetString("BaseTypeFormatter.template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace {{Namespace}}
        ///{
        ///	using MessagePack;
        ///	using MessagePack.Formatters;
        ///	using MessagePack.Resolvers;
        ///
        ///	{{code}}
        ///}.
        /// </summary>
        internal static string Common_template {
            get {
                return ResourceManager.GetString("Common.template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ConcreteTypeFormatter_template {
            get {
                return ResourceManager.GetString("ConcreteTypeFormatter.template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string EnumFormatter_template {
            get {
                return ResourceManager.GetString("EnumFormatter.template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to public static class MessagePackSerializerOptionsExtensions
        ///{
        ///	public static MessagePackSerializerOptions Add(this MessagePackSerializerOptions self)
        ///		=&gt; self.WithResolver(CompositeResolver.Create(new IMessagePackFormatter[]
        ///		{
        ///			&lt;# foreach (var formatter in Formatters) { #&gt;
        ///			new &lt;#= formatter #&gt;(),
        ///			&lt;# } #&gt;
        ///		}, new[] { self.Resolver }));
        ///}.
        /// </summary>
        internal static string Extensions_template {
            get {
                return ResourceManager.GetString("Extensions.template", resourceCulture);
            }
        }
    }
}
